// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swgtedaeomqmimmmisey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Z3RlZGFlb21xbWltbW1pc2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjU5NzMsImV4cCI6MjA2MDc0MTk3M30.cYmH0IbjDBICgsUpttUApvVJ5dn60WjNhmZGWnpVunw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);